#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CrmCross.Droid.Resource", IsApplication=true)]

namespace CrmCross.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::CrmCross.Android.Resource.Id.OptionHostName = global::CrmCross.Droid.Resource.Id.OptionHostName;
			global::CrmCross.Android.Resource.Id.OptionPort = global::CrmCross.Droid.Resource.Id.OptionPort;
			global::CrmCross.Android.Resource.Id.OptionRemoteServer = global::CrmCross.Droid.Resource.Id.OptionRemoteServer;
			global::CrmCross.Android.Resource.Id.OptionsButton = global::CrmCross.Droid.Resource.Id.OptionsButton;
			global::CrmCross.Android.Resource.Id.ResultFullName = global::CrmCross.Droid.Resource.Id.ResultFullName;
			global::CrmCross.Android.Resource.Id.ResultMessage = global::CrmCross.Droid.Resource.Id.ResultMessage;
			global::CrmCross.Android.Resource.Id.ResultResultState = global::CrmCross.Droid.Resource.Id.ResultResultState;
			global::CrmCross.Android.Resource.Id.ResultRunSingleMethodTest = global::CrmCross.Droid.Resource.Id.ResultRunSingleMethodTest;
			global::CrmCross.Android.Resource.Id.ResultStackTrace = global::CrmCross.Droid.Resource.Id.ResultStackTrace;
			global::CrmCross.Android.Resource.Id.ResultsFailed = global::CrmCross.Droid.Resource.Id.ResultsFailed;
			global::CrmCross.Android.Resource.Id.ResultsId = global::CrmCross.Droid.Resource.Id.ResultsId;
			global::CrmCross.Android.Resource.Id.ResultsIgnored = global::CrmCross.Droid.Resource.Id.ResultsIgnored;
			global::CrmCross.Android.Resource.Id.ResultsInconclusive = global::CrmCross.Droid.Resource.Id.ResultsInconclusive;
			global::CrmCross.Android.Resource.Id.ResultsMessage = global::CrmCross.Droid.Resource.Id.ResultsMessage;
			global::CrmCross.Android.Resource.Id.ResultsPassed = global::CrmCross.Droid.Resource.Id.ResultsPassed;
			global::CrmCross.Android.Resource.Id.ResultsResult = global::CrmCross.Droid.Resource.Id.ResultsResult;
			global::CrmCross.Android.Resource.Id.RunTestsButton = global::CrmCross.Droid.Resource.Id.RunTestsButton;
			global::CrmCross.Android.Resource.Id.TestSuiteListView = global::CrmCross.Droid.Resource.Id.TestSuiteListView;
			global::CrmCross.Android.Resource.Id.agentWebView = global::CrmCross.Droid.Resource.Id.agentWebView;
			global::CrmCross.Android.Resource.Layout.options = global::CrmCross.Droid.Resource.Layout.options;
			global::CrmCross.Android.Resource.Layout.results = global::CrmCross.Droid.Resource.Layout.results;
			global::CrmCross.Android.Resource.Layout.test_result = global::CrmCross.Droid.Resource.Layout.test_result;
			global::CrmCross.Android.Resource.Layout.test_suite = global::CrmCross.Droid.Resource.Layout.test_suite;
			global::CrmCross.Android.Resource.Layout.WebAuthenticationBroker = global::CrmCross.Droid.Resource.Layout.WebAuthenticationBroker;
			global::CrmCross.Android.Resource.String.ApplicationName = global::CrmCross.Droid.Resource.String.ApplicationName;
			global::CrmCross.Android.Resource.String.Hello = global::CrmCross.Droid.Resource.String.Hello;
			global::CrmCross.Android.Resource.String.library_name = global::CrmCross.Droid.Resource.String.library_name;
			global::Microsoft.IdentityModel.Clients.ActiveDirectory.Resource.Id.agentWebView = global::CrmCross.Droid.Resource.Id.agentWebView;
			global::Microsoft.IdentityModel.Clients.ActiveDirectory.Resource.Layout.WebAuthenticationBroker = global::CrmCross.Droid.Resource.Layout.WebAuthenticationBroker;
			global::Microsoft.IdentityModel.Clients.ActiveDirectory.Resource.String.ApplicationName = global::CrmCross.Droid.Resource.String.ApplicationName;
			global::TestyDroid.Android.Resource.Id.OptionHostName = global::CrmCross.Droid.Resource.Id.OptionHostName;
			global::TestyDroid.Android.Resource.Id.OptionPort = global::CrmCross.Droid.Resource.Id.OptionPort;
			global::TestyDroid.Android.Resource.Id.OptionRemoteServer = global::CrmCross.Droid.Resource.Id.OptionRemoteServer;
			global::TestyDroid.Android.Resource.Id.OptionsButton = global::CrmCross.Droid.Resource.Id.OptionsButton;
			global::TestyDroid.Android.Resource.Id.ResultFullName = global::CrmCross.Droid.Resource.Id.ResultFullName;
			global::TestyDroid.Android.Resource.Id.ResultMessage = global::CrmCross.Droid.Resource.Id.ResultMessage;
			global::TestyDroid.Android.Resource.Id.ResultResultState = global::CrmCross.Droid.Resource.Id.ResultResultState;
			global::TestyDroid.Android.Resource.Id.ResultRunSingleMethodTest = global::CrmCross.Droid.Resource.Id.ResultRunSingleMethodTest;
			global::TestyDroid.Android.Resource.Id.ResultStackTrace = global::CrmCross.Droid.Resource.Id.ResultStackTrace;
			global::TestyDroid.Android.Resource.Id.ResultsFailed = global::CrmCross.Droid.Resource.Id.ResultsFailed;
			global::TestyDroid.Android.Resource.Id.ResultsId = global::CrmCross.Droid.Resource.Id.ResultsId;
			global::TestyDroid.Android.Resource.Id.ResultsIgnored = global::CrmCross.Droid.Resource.Id.ResultsIgnored;
			global::TestyDroid.Android.Resource.Id.ResultsInconclusive = global::CrmCross.Droid.Resource.Id.ResultsInconclusive;
			global::TestyDroid.Android.Resource.Id.ResultsMessage = global::CrmCross.Droid.Resource.Id.ResultsMessage;
			global::TestyDroid.Android.Resource.Id.ResultsPassed = global::CrmCross.Droid.Resource.Id.ResultsPassed;
			global::TestyDroid.Android.Resource.Id.ResultsResult = global::CrmCross.Droid.Resource.Id.ResultsResult;
			global::TestyDroid.Android.Resource.Id.RunTestsButton = global::CrmCross.Droid.Resource.Id.RunTestsButton;
			global::TestyDroid.Android.Resource.Id.TestSuiteListView = global::CrmCross.Droid.Resource.Id.TestSuiteListView;
			global::TestyDroid.Android.Resource.Layout.options = global::CrmCross.Droid.Resource.Layout.options;
			global::TestyDroid.Android.Resource.Layout.results = global::CrmCross.Droid.Resource.Layout.results;
			global::TestyDroid.Android.Resource.Layout.test_result = global::CrmCross.Droid.Resource.Layout.test_result;
			global::TestyDroid.Android.Resource.Layout.test_suite = global::CrmCross.Droid.Resource.Layout.test_suite;
			global::TestyDroid.Android.Resource.String.ApplicationName = global::CrmCross.Droid.Resource.String.ApplicationName;
			global::TestyDroid.Android.Resource.String.Hello = global::CrmCross.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int accessToken = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int agentWebView = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int loginButton = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int loginUsernamePasswordButton = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int WebAuthenticationBroker = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
